name: CSpleef
main: com.comze_instancelabs.cspleef.Main
version: 1.0
author: instancelabs
permissions:
  cspleef.sign:
    description: Gives access to create signs for joining games.
commands:
   cspleef:
      description: Main command
      usage: /cspleef [name]
